spring:
  application:
    name: feign-client

server:
  port: 8086

eureka:
  instance:
    appname: feign-client
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
feign:
  hystrix:
    enabled: true